import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { getCurrentUser } from '@/lib/auth';
import { db } from '@/lib/db';
import { money } from '@/lib/money';
import { logout } from '@/app/actions';

export default async function MonthPage({ params }: { params: Promise<{ year: string; month: string }> }) {
  const user = await getCurrentUser(); if (!user) redirect('/login'); const { year: yearText, month: monthText } = await params; const year = Number(yearText); const month = Number(monthText); if (!year || month < 1 || month > 12) notFound();
  const start = `${year}-${String(month).padStart(2, '0')}-01`; const endDate = new Date(year, month, 0); const end = `${year}-${String(month).padStart(2, '0')}-${String(endDate.getDate()).padStart(2, '0')}`;
  const records = await db.dailyRecord.findMany({ where: { userId: user.id, recordDate: { gte: start, lte: end } }, include: { transactions: true }, orderBy: { recordDate: 'asc' } });
  const transactions = records.flatMap((record) => record.transactions); const credits = transactions.filter((transaction) => Number(transaction.amount) > 0).reduce((sum, transaction) => sum + Number(transaction.amount), 0); const debits = transactions.filter((transaction) => Number(transaction.amount) < 0).reduce((sum, transaction) => sum + Math.abs(Number(transaction.amount)), 0);
  return <main className="app-page"><nav className="topbar"><Link href="/dashboard" className="wordmark"><span className="brand-mark small">DL</span><span>Daily Ledger</span></Link><form action={logout}><button className="logout-button">Sign out</button></form></nav><div className="content-wrap"><Link className="back-link" href={`/year/${year}`}>← {year}</Link><header className="page-heading compact"><div><p className="eyebrow">MONTHLY LEDGER</p><h1>{new Date(year, month - 1).toLocaleString('en-US', { month: 'long' })} <span>{year}</span></h1><p className="subheading">Select a date to open its ledger.</p></div><div className="month-total"><span>Net movement</span><strong>{money(credits - debits)}</strong></div></header><div className="summary-cards"><div><span>Credits</span><strong className="credit">+{money(credits)}</strong></div><div><span>Debits</span><strong className="debit">-{money(debits)}</strong></div><div><span>Recorded days</span><strong>{records.length}</strong></div></div><div className="date-list"><div className="date-list-head"><span>Date</span><span>Day</span><span>Status</span><span>Opening</span><span>Closing</span></div>{Array.from({ length: endDate.getDate() }, (_, index) => { const day = index + 1; const date = `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`; const record = records.find((item) => item.recordDate === date); const dateObj = new Date(year, month - 1, day); const future = date > new Date().toISOString().slice(0, 10); return <Link href={`/year/${year}/month/${month}/date/${day}`} className="date-row" key={date}><strong>{String(day).padStart(2, '0')}</strong><span>{dateObj.toLocaleDateString('en-US', { weekday: 'long' })}</span><span className={record?.status === 'CLOSED' ? 'status closed' : future ? 'status future' : 'status open'}>{record?.status === 'CLOSED' ? 'Closed' : future ? 'Future date' : 'Open'}</span><span>{money(record?.openingBalance || 0)}</span><span>{money(record?.closingBalance || 0)} <b>↗</b></span></Link>})}</div></div></main>;
}
