import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { getCurrentUser } from '@/lib/auth';
import { db } from '@/lib/db';
import { dateKey, money } from '@/lib/money';
import { logout } from '@/app/actions';
import LedgerTable from '@/components/ledger-table';

export default async function DatePage({ params }: { params: Promise<{ year: string; month: string; day: string }> }) {
  const user = await getCurrentUser(); if (!user) redirect('/login'); const { year: yearText, month: monthText, day: dayText } = await params; const year = Number(yearText); const month = Number(monthText); const day = Number(dayText); if (!year || month < 1 || month > 12 || day < 1 || day > 31) notFound();
  const date = dateKey(year, month, day); const dateObj = new Date(year, month - 1, day); if (dateObj.getFullYear() !== year || dateObj.getMonth() !== month - 1 || dateObj.getDate() !== day) notFound();
  let record = await db.dailyRecord.findUnique({ where: { userId_recordDate: { userId: user.id, recordDate: date } }, include: { transactions: { orderBy: { transactionNumber: 'asc' } } } });
  const previous = await db.dailyRecord.findFirst({ where: { userId: user.id, recordDate: { lt: date } }, orderBy: { recordDate: 'desc' } });
  const opening = record ? Number(record.openingBalance) : Number(previous?.closingBalance || 0); const future = date > new Date().toISOString().slice(0, 10);
  if (!record && !future) record = await db.dailyRecord.create({ data: { userId: user.id, recordDate: date, openingBalance: opening, closingBalance: opening }, include: { transactions: true } });
  const entries = (record?.transactions || []).reduce<{ id: string; transactionNumber: number; transactionTime: string; description: string; amount: number; balance: number }[]>((result, transaction) => { const prior = result.at(-1)?.balance ?? opening; result.push({ id: transaction.id, transactionNumber: transaction.transactionNumber, transactionTime: transaction.transactionTime.toISOString(), description: transaction.description, amount: Number(transaction.amount), balance: prior + Number(transaction.amount) }); return result; }, []);
  const displayRecord = record || { id: 'future', status: 'OPEN' as const, closingBalance: opening, openingBalance: opening };
  return <main className="app-page"><nav className="topbar"><Link href="/dashboard" className="wordmark"><span className="brand-mark small">DL</span><span>Daily Ledger</span></Link><div className="topbar-right"><Link href={`/year/${year}/month/${month}`} className="nav-link">Back to month</Link><form action={logout}><button className="logout-button">Sign out</button></form></div></nav><div className="content-wrap ledger-page"><Link className="back-link" href={`/year/${year}/month/${month}`}>← {dateObj.toLocaleString('en-US', { month: 'long' })} {year}</Link><header className="ledger-heading"><div><p className="eyebrow">DAILY RECORD</p><h1>{dateObj.toLocaleDateString('en-US', { day: '2-digit', month: 'long', year: 'numeric' })}</h1><p className="day-label">{dateObj.toLocaleDateString('en-US', { weekday: 'long' })}</p></div><div className="day-state">{future ? <><span className="status future">Future date</span><p>Entries unlock on this date.</p></> : displayRecord.status === 'CLOSED' ? <><span className="locked-label">⌾ DAY CLOSED</span><p>Read-only historical record</p></> : <><span className="status open">● Open</span><p>Entries are being accepted</p></>}</div></header><div className="ledger-summary"><div><span>Opening balance</span><strong>{money(displayRecord.openingBalance)}</strong></div><div><span>Transactions</span><strong>{entries.length}</strong></div><div><span>Closing balance</span><strong>{money(displayRecord.closingBalance)}</strong></div></div>{record && !future ? <LedgerTable recordId={record.id} date={date} year={year} month={String(month)} day={String(day)} opening={Number(displayRecord.openingBalance)} closing={Number(displayRecord.closingBalance)} status={displayRecord.status} entries={entries} /> : <div className="future-panel"><span className="future-icon">◷</span><h2>This date has not arrived</h2><p>Your ledger will be ready for entries on {dateObj.toLocaleDateString('en-US', { month: 'long', day: 'numeric' })}.</p></div>}</div></main>;
}
